from typing import List, Any, Dict, Optional, TypedDict, Literal
from pydantic import BaseModel, Field

class DataEngineerRequest(BaseModel):
    abstraction: str = Field(description="JSON representation of the abstracted dataset sample") 
    dataset_name: str = Field(description="Name of the source dataset")
    task: str = Field(description="User task description in natural language")

class DataAnalystRequest(BaseModel):
    abstraction: str = Field(description="JSON representation of the abstracted dataset sample") 
    task: str = Field(description="User data analysis query in natural language")

class Plan(BaseModel):
    """The transformation plan to be parsed and applied onto the abstraction"""
    id : str = Field(description="Plan identifier")
    task : str = Field(description="User supplied data engineering task description summary")
    dataset_name : str = Field(description="Name of the dataset targeted by the plan")
    flowetl_schema : Dict[str, str] = Field(description="Inferred flowetl_schema for the input abstraction, using native Pandas data types")
    pipeline : List[Any] = Field(description="FlowETL functions to be applied onto the dataset")

class Analysis(BaseModel):
    """The data analyis response model from the data analysis agent"""
    analysis_code : str = Field(description="Pandas code to carry out the analysis task")
    plot_code : Optional[str] = Field(None, description="Matplotlib code with labels and formatting") 

class Feedback(BaseModel):
    """The feedback generated by the validator agent"""
    validation : Dict[str, Any] = Field("Validation feedback composed of errors, warnings, and validation summary")

class GraphState(TypedDict, total=False):
    """The state of the Producer-Validator LangGraph graph"""
    task: str = Field(description="User supplied data engineering task description summary")
    abstraction : str = Field(description="JSON representation of the abstracted dataset sample")                       
    pipeline: Dict[str, Any] = Field("Latest pipeline of FlowETL functions generated by the producer")
    validation: Dict[str, Any] = Field("Latest feedback from validator")
    iterations: int = Field(description="Iterations through the producer-validator graph")                   
    flowetl_schema : Dict[str, str] = Field(description="Inferred flowetl_schema for the input abstraction, using native Pandas data types")
    dataset_name : str  = Field(description="Name of the dataset targeted by the plan")
    exit_reason: Literal["ERROR", "DONE", "FAIL"] = Field("Attribute used to track the graph state.")